---

- name: Creating mountable shared folders
  file: 
    path: /var/nfs/kubedata
    owner: nobody
    group: nogroup
    state: directory

- name: Configure nfs server
  copy:
    dest: /etc/exports
    content: |
      /var/nfs/kubedata *(rw,sync,no_subtree_check,no_root_squash,no_all_squash)
      
- name: Configure nfs server
  ansible.builtin.shell:
    cmd: exportfs -ra

- name: Starting nfs server
  service:
    name: nfs-server 
    state: started
    enabled: yes

- name: Add nfs provisioner helm chart repo
  become_user: ubuntu
  ansible.builtin.shell:
    cmd: helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner

- name: Update helm repos
  become_user: ubuntu
  ansible.builtin.shell:
    cmd: helm repo update

- name: Deploy nfs provisioner with helm
  become_user: ubuntu
  kubernetes.core.helm:
    name: nfs-provisioner
    chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    release_namespace: default
    values:
      nfs:
        server: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        path: /var/nfs/kubedata
      storageClass:
        defaultClass: true

# - name: Add default storage class for NFS provisioner
#   become_user: ubuntu
#   k8s:
#     state: present
#     definition:
#       apiVersion: storage.k8s.io/v1 
#       kind: StorageClass 
#       metadata: 
#         name: nfs-sc
#         annotations: 
#           storageclass.kubernetes.io/is-default-class: "true" 
#       provisioner: cluster.local/nfs-subdir-external-provisioner 
#       allowVolumeExpansion: true 
#       parameters: 
#         archiveOnDelete: "false"
